config/routes.rb
Rails.application.routes.draw do
  get "/" => "seguros#homepage", :as => "root"
  get "solucoes" => "seguros#solucoes", :as => "solucoes"
  get "negocios" => "seguros#negocios", :as => "exclusivos"
  devise_for :admins
  get 'seguros/search' => 'seguros#search', as: 'search_seguros'
  get 'seguros/index' => 'seguros#index', as: 'seguros'
  post 'seguros/index' => 'seguros#create'
  resources :seguros
  resources :contacts, only: [:new, :create]
  get "contacts" => "contacts#new"
  resources :teams, :path => "contactos"
  resources :seguroscontacts, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base


  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base

  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :valitade => true
  attribute :nickname, :captcha => true

  def headers
    {
    :subject => "Mensagem",
    :to => "geral@be-seguro.com",
    :from => %("#{name}" <#{email}>)
  }

end
end

app/models/seguro.rb
class Seguro < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged


  has_one :seguroscontact

  mount_uploader :image, ImageUploader

  def self.search(search)
    where(['name LIKE ?', "%#{search}%"])

end

def should_generate_new_friendly_id?
  new_record?
end

end

app/models/seguroscontact.rb
class Seguroscontact < MailForm::Base

  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :valitade => true
  attribute :nickname, :captcha => true
  attribute :seguro



  def headers
    {
    :subject => "Mensagem",
    :to => "geral@be-seguro.com",
    :from => %("#{name}" <#{email}>)
  }

end

end

app/models/team.rb
class Team < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def contact
      @contact = Contact.new
    end

    def set_seguro
      @seguro = Seguro.friendly.find(params[:id])
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = "Erro"
      render :new
    end
  end
end

app/controllers/seguros_controller.rb
class SegurosController < ApplicationController
  before_action :set_seguro, only: [:edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :edit, :update, :destroy]


  # GET /seguros
  # GET /seguros.json
  def index
    @seguros = Seguro.search(params[:search])
  end

  # GET /seguros/1
  # GET /seguros/1.json
  def show
    @seguro = Seguro.friendly.find(params[:id])
  end

  # GET /seguros/new
  def new
    @seguro = Seguro.new
  end

  # GET /seguros/1/edit
  def edit
  end

  # POST /seguros
  # POST /seguros.json
  def create
    @seguro = Seguro.new(seguro_params)

    respond_to do |format|
      if @seguro.save
        format.html { redirect_to @seguro, notice: 'Seguro was successfully created.' }
        format.json { render :index}
      else
        format.html { render :new }
        format.json { render json: @seguro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seguros/1
  # PATCH/PUT /seguros/1.json
  def update
    respond_to do |format|
      if @seguro.update(seguro_params)
        format.html { redirect_to @seguro, notice: 'Seguro was successfully updated.' }
        format.json { render :show, status: :ok, location: @seguro }
      else
        format.html { render :edit }
        format.json { render json: @seguro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seguros/1
  # DELETE /seguros/1.json
  def destroy
    @seguro.destroy
    respond_to do |format|
      format.html { redirect_to seguros_url, notice: 'Seguro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def homepage
  @seguros = Seguro.all
  end

      def solucoes

    end

    def negocios
      @seguros = Seguro.all



    end

    def seguroscontact
      @seguroscontact = Seguroscontact.new
    end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seguro
      @seguro = Seguro.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seguro_params
      params.require(:seguro).permit(:name, :description, :image, :tipo, :destaque, :shortdescription)
    end
end

app/controllers/seguroscontacts_controller.rb
class SeguroscontactsController < ApplicationController

  def new
    @seguroscontact = Seguroscontact.new
  end

  def create

     @seguroscontact = Seguroscontact.new(params[:seguroscontact])
     @seguroscontact.request = request
        if @seguroscontact.deliver
          flash.now[:error] = nil
        else
          flash.now[:error] = "Erro"
          render :new
        end
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :description, :picture, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/seguros_helper.rb
module SegurosHelper
end

app/helpers/seguroscontacts_helper.rb
module SeguroscontactsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/contacts/_form.html.erb
<%= form_for Contact.new do |f| %>

    <h4 style="margin-bottom:-10px;"><%= f.label :nome %></h4><br>
    <%= f.text_field :name, required: true, class: 'in'  %><br>

   <h4 style="margin-bottom:-10px;"><%= f.label :email %></h4><br>
    <%= f.email_field :email, required: true, class: 'in' %><br>

   <h4 style="margin-bottom:-10px;""><%= f.label :mensagem %></h4><br>
    <%= f.text_area :message, as: :text, required: true, class: 'inmes', rows: '5'  %><br>

    <div class="hidden">

    <%= f.label :nickname %><br>
    <%= f.text_field :nickname, hint: "leave this field blank"  %><br>

    </div>

    <%= f.submit 'Enviar Mensagem', class: 'button enviar' %>

    <% end %>

app/views/contacts/create.html.erb
<div class="home">
<div style="position:relative; top:20%;">


  <h3 class="thank">
    Obrigado pela sua mensagem, entraremos em contacto em breve!
  </h3>




</div>

app/views/contacts/new.html.erb
<div class="home">
<div style="text-align: center; ">
  <%= image_tag ("contactos.jpg"), :class => "ban", :style => "width: 100%;
        object-fit: cover;
        max-height:800px;
        overflow: hidden;
        margin-top: 0; " %>

        <h1 style="margin-top: -30%; color: white; font-weight: bold; text-shadow: 1px 1px black; font-size: 80px;">Contactos</h1>

  </div>



<h5 class="cont" style="text-align: center; padding: 40px; color: white; font-size: 20px; margin-top:30%;"> Esclareça as suas dúvidas <br>Contacte-nos</h5>

<div class="container" style="margin-top: 100px; margin-bottom: 200px;">

  <div class="row">
<div class="col-sm">

    <%= form_for @contact do |f| %>

    <h4 style="margin-bottom:-10px;"><%= f.label :nome %></h4><br>
    <%= f.text_field :name, required: true, class: 'in'  %><br>

   <h4 style="margin-bottom:-10px;"><%= f.label :email %></h4><br>
    <%= f.email_field :email, required: true, class: 'in' %><br>

   <h4 style="margin-bottom:-10px;""><%= f.label :mensagem %></h4><br>
    <%= f.text_area :message, as: :text, required: true, class: 'inmes', rows: '5'  %><br>

    <div class="hidden">

    <%= f.label :nickname %><br>
    <%= f.text_field :nickname, hint: "leave this field blank"  %><br>

    </div>


    <%= f.submit 'Enviar Mensagem', class: 'button enviar' %>

    <% end %>
  </div>

<!--<form action="https://formspree.io/francisco.gaivao@outlook.com"
      method="POST">


      <h5 style="margin-left: 5%">Nome</h5>
      <input class="in" type="text" name="name" required><br>
      <h5 style="margin-left: 5%">Email</h5>
    <input class="in" type="email" name="_replyto" required><br>
    <h5 style="margin-left: 5%" >Mensagem</h5>
      <input class="in" type="text"  name="observação" style="height: 100px; width: 250px; word-break: break-all;"><br>
      <input style="margin-left: 5%" class="check" type="checkbox" name="rgpd" value="aceito" required> &nbsp&nbsp&nbsp Aceito que a Bé Seguro trate <br>os meus dados pessoais para uso exclusivo comercial<br>
      <input type="hidden" name="_next" value="http://localhost:3000" />
    <input style= "margin: 40px; cursor: pointer;" type="submit" value="Enviar" class="enviar">
</form>


</div>-->






<div class="col-sm" style="float:right !important">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3104.8935105549267!2d-9.145969491532334!3d38.70631226526962!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd1935d5071a0485%3A0x19e09df7c5c89f66!2sB%C3%A9%20Seguro%20Sociedade%20Mediadora%20De%20Seguros%2C%20Lda.!5e0!3m2!1spt-PT!2spt!4v1568237871530!5m2!1spt-PT!2spt" width="100%" height="550" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bé-Seguro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="description" content="A Bé-Seguro traz-lhe as melhores campanhas e os melhores seguros
    para si para a sua familia e para o seu trabalho" />
    <meta name="robots" content="all" />
    <meta name="googlebot" content="all" />
    <meta name="keywords" content="be-seguro,seguros,trabalho,familia,portugal,automóvel">
    <meta property="og:image" content="BeSeguro.png">
    <%= favicon_link_tag 'logoaz.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>


    <link href="https://fonts.googleapis.com/css?family=Titillium+Web&display=swap" rel="stylesheet">


    <div class="navbardes" style="position: fixed; width: 100%; background-color: #434f5b; padding-bottom: 20px; z-index:5 !important; font-size: 50px; margin-top: 0">
          <ul  class="nav navbar-nav" style="display: block; float:right; ">
            <span><%= link_to root_path do %> <%= image_tag ("7.png"), :class => ('logo'), :style => (" width: 190px; margin-right: 15%; margin-left: 40px; padding-top: 20px;float:left")%><% end %></span>
            <li id='nav'><a style="font-size:20px; margin-right: 90px;" class="smoothscroll" href="/#sobrenos"> Sobre Nós</a></li>
            <li id='nav'><%= link_to "Produtos", solucoes_path%></li>
            <li id='nav'><%= link_to "Contactos", contacts_path%></li>
            <li id='nav'><%= link_to "Employee Benefits", exclusivos_path%></li>
            <li id="navmobile" style="font-size:50px; float:right;"> <i class="fa fa-bars"></i></li>
  </a>
          </ul>
        </div>




        <script>
$(document).ready(function() {

            $('.navmobileanchor').hide();

            $("#navmobile").click(function(){
               $(".navmobileanchor").toggle( 'slow', function(){
               });
            });
         });
</script>
  </head>

  <body>

    <ul  class="navmobileanchor" style="position: fixed; margin-top: 160px; float:right;">
            <li  style="font-size: 27px !important; margin-top: 10px" id='mb'> Sobre Nós</li>
            <li id='mb' style="color:white !important; font-size: 25px !important; margin-top: 10px"><%= link_to "Produtos", solucoes_path%></li>
            <li  style="font-size: 27px !important; margin-top: 10px" id='mb'><%= link_to "Contactos", contacts_path%></li>
            <li id='mb' style="font-size: 27px !important;margin-top: 10px"><a style="font-size:27px !important;"><%= link_to "Employee Benefits", exclusivos_path%></li>
          </ul>

    <%= yield %>


  </body>


<footer style="text-align: center; padding-top: 20px; background-color: #22282e; ">

  <h2 style="margin-bottom: 40px;">Contactos</h2>
  <table align= "center" style="width: 50%;">
    <tbody>
      <tr>

    <th class="ft">
    <i class="fas fa-envelope" style= "font-size: 20px;"></i>
  <h5 style="text-align: center;">geral@be-seguro.com</h5>
</th>
<th class="ft" style="color: white;">
  <i class="fas fa-map-marker-alt" style= "font-size: 20px;"></i>
  <h5 style="text-align: center;">Av. 24 de Julho 1 - 2º Esq. <br>1200-478 Lisboa</h5>
    </th>
  <th class="ft">
  <i class="fas fa-phone" style= "font-size: 20px;"></i>
  <h5 style="text-align: center;">+351 214 585 270</h5>
</th>
</tr>
  </table>
  </footer>


</html>

app/views/seguros/_form.html.erb
<div style="height:100%">

  <div style="text-align:center;">

<%= form_with(model: seguro, local: true) do |form| %>
  <% if seguro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seguro.errors.count, "error") %> prohibited this seguro from being saved:</h2>

      <ul>
      <% seguro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div style="width: 50%; text-align:center; margin-left: 25%;">

  <div class="field">
    <%= form.label :nome %><br>
    <%= form.text_field :name, class: 'in' %>
  </div>

  <div class="field">
    <%= form.label :descrição %><br>
    <%= form.text_area :description, rows: '5', col:'20', class: 'in' %>
  </div>

  <div class="field">
    <%= form.label :imagem %><br>
    <%= form.file_field :image, style: "margin-left: 30%" %>

  </div>

  <div class="field">
    <%= form.label :tipo %><br>
    <%= form.select :tipo, ['Particular', 'Empresa', 'Negocio']%>
  </div>
<div class="field">
  <%= form.label "Destaque?" %> <br />
    <%= form.check_box :destaque %> <br />
    </div>

    <div class="field">
    <%= form.label :shortdescription %><br>
    <%= form.text_area :shortdescription, rows: '3', col:'20', class: 'in' %>
  </div>

  <div class="actions" style="margin-top:50px;">
    <%= form.submit %>
  </div>
<% end %>

</div>

</div>

</div>

app/views/seguros/edit.html.erb
<div class="home">

<h1 style="margin-top:20%">Editing Seguro</h1>

<%= render 'form', seguro: @seguro %>

<%= link_to 'Show', @seguro %> |
<%= link_to 'Back', seguros_path %>

app/views/seguros/index.html.erb
<div class="home">

   <div style="text-align:center;">
   <%= form_tag seguros_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], class: 'searchfield', style: 'color:black !important' %><br>
    <%= submit_tag "Encontrar o meu seguro", :name => nil, class: 'searchbutton' %>
  </p>
<% end %>
</div>


<div class="container" style="margin-bottom: 200px; color:black !important;">
  <div class="row">
    <div class="col-sm" id="seguroslista" style="text-align:center; ">

      <ul style="color:black !important;">
<li><h3 style="margin-bottom: 20px;">Empresas</h3></li>





    <% @seguros.where(tipo: 'Empresa').each do |seguro| %>

 <%= link_to seguro do %>

   <li style="color:black !important; font-size:17px;"><%= seguro[:name] %></li><br>
   <% end %>
   <% if admin_signed_in? %>

    <a style="color: black !important;">  <%= link_to 'Edit', edit_seguro_path(seguro) %></a>
   <a style="color: black !important;">  <%= link_to 'Destroy', seguro, method: :delete, data: { confirm: 'Are you sure?' } %></a>
  <% end %>
  <% end %>
</li>
   </ul>

</div>





<div class="col-sm" style="text-align:center;">
  <ul style="color:black !important; ">
<li><h3 style="margin-bottom: 20px;">Particular</h3></li>




     <% @seguros.where(tipo: 'Particular').each do |seguro| %>

 <%= link_to seguro do %>

   <li style="color:black !important; text-align:center; font-size:17px; "><%= seguro[:name] %></li><br>
   <% end %>
   <% if admin_signed_in? %>

    <a style="color: black !important;">  <%= link_to 'Edit', edit_seguro_path(seguro) %></a>
   <a style="color: black !important;">  <%= link_to 'Destroy', seguro, method: :delete, data: { confirm: 'Are you sure?' } %></a>
  <% end %>
  <% end %>
</li>
   </ul>
</div>
</div>
</div>




<br>
<% if admin_signed_in? %>

 <li> <%= link_to('Logout', destroy_admin_session_path, method: :delete) %></li>

<% end %>

<% if admin_signed_in? %>
<li><%= link_to 'New Seguro', new_seguro_path %></li>
<% end %>

app/views/seguros/negocios.html.erb
<div class="home">




<div style="padding-top: 200px; margin-bottom: 200px;">
  <div class="container">
    <ul>
     <li> <% @seguros.where(tipo: 'Negocio').each do |seguro| %>

 <%= link_to seguro do %>

   <h1 style=" position:absolute; color: white; font-size: 70px; font-weight: 900; text-shadow: 2px 2px black"><%= seguro[:name] %></h1><%= image_tag seguro.image.thumb.url, :class => "style_image" %>
   <% end %>
   <% if admin_signed_in? %>

    <a style="color: black !important;">  <%= link_to 'Edit', edit_seguro_path(seguro) %></a>
   <a style="color: black !important;">  <%= link_to 'Destroy', seguro, method: :delete, data: { confirm: 'Are you sure?' } %></a>
  <% end %>
  <% end %>
</li>
   </ul>


</div>

<div>
  <div class="container">
    <ul>
     <li>


   <h1 style=" position:absolute; color: white; font-size: 70px; font-weight: 900; text-shadow: 2px 2px black">Employee Benefits</h1><%= image_tag ("employee.png"), :class => "style_image" %>

</li>
   </ul>


</div>






</div>

app/views/seguros/new.html.erb
<div class="home">

<h1 style="padding-top: 150px;">Novo Seguro</h1>

<div style="margin-top: 100px">

<%= render 'form', seguro: @seguro %>

<%= link_to 'Back', seguros_path %>
<div class="topnav" id="myTopnav">
    <div class="w3-container w3-center w3-animate-left">
    <a href="#home">Home</a>
    <%= link_to "Seguros", seguros_path, :class => "active"%>
    <%= link_to "Contactos", teams_path%>
    <a href="#about">About</a>
    <a href="javascript:void(0);" class="icon" onclick="myFunction()">
      <i class="fa fa-bars"></i>
    </a>
  </div>
  </div>
  <div class="topnav" id="myTopnav">
    <div class="w3-container w3-center w3-animate-left">
    <%= link_to "Home", root_path%>
    <%= link_to "Seguros", seguros_path, :class => "active"%>
    <%= link_to "Contactos", teams_path%>
    <a href="#about">About</a>
    <a href="javascript:void(0);" class="icon" onclick="myFunction()">
      <i class="fa fa-bars"></i>
    </a>
  </div>
  </div>
  </div>

app/views/seguros/show.html.erb
<div class="home">

  <div>
    <%= image_tag @seguro.image.thumb.url, :class => "style_image"%>
  </div>

  <div style="margin-left: 50px; margin-top: 100px;">
  <h3 style="margin-bottom: 30px; text-align:center;"><%= @seguro.name %></h3>

   </div>

  <hr>

  <div style="margin-top: 80px;">

 <p style="font-size: 20px; width: 70%; margin: auto; text-align:center;"> <%= @seguro.description %></p>

</div>





<% if @admin_signed_in %>
<%= link_to 'Edit', edit_seguro_path(@seguro) %>
<% end %>




  <div class="tform" style="margin-bottom:100px;">

    <p>Preencha o formulário e entraremos em contacto em breve</p>


<div class="form">

<div class="sform" style="width:70%; margin: auto; height: 100%;">
    <%= form_for Seguroscontact.new do |f| %>

    <h4 style="margin-bottom:-10px;"><%= f.label :nome %></h4><br>
    <%= f.text_field :name, required: true, class: 'in'  %><br>

   <h4 style="margin-bottom:-10px;"><%= f.label :email %></h4><br>
    <%= f.email_field :email, required: true, class: 'in' %><br>

   <h4 style="margin-bottom:-10px;""><%= f.label :mensagem %></h4><br>
    <%= f.text_area :message, as: :text, required: true, class: 'inmes', rows: '5'  %><br>
    <div style="visibility: hidden;">
    <%= f.text_area :seguro, value: @seguro.name %><br>
  </div>
    <div class="hidden">

    <%= f.label :nickname %><br>
    <%= f.text_field :nickname, hint: "leave this field blank"  %><br>


    </div>

    <%= f.submit 'Enviar Mensagem', class: 'button enviar' %>

    <% end %>
</div>

</div>

</div>

app/views/seguros/solucoes.html.erb
<div class="home">

<div style="text-align: center; ">
  <%= image_tag ("sol.jpg"), :class => "ban", :style => "width: 100%;
        object-fit: cover;
        max-height:800px;
        overflow: hidden;
        margin-top: 0; " %>

        <h1 style="margin-top: -30%; color: white; font-weight: bold; text-shadow: 1px 1px black; font-size: 80px;">Soluções</h1>

  </div>
   <div style="margin-top:30%; ">

  <div style="text-align:center; margin-top: 100px;">
  <h3 style="margin-bottom: 30px">Soluções</h3>
</div>


  <div>
  <hr>
  <p style="font-size: 20px; margin:auto; text-align:center; margin-bottom: 100px; margin-top: 100px;">Aqui pode encontrar as soluções para se proteger de todas as imprevisibilidades do dia a dia.<br>
  Soluções para si, para a sua empresa e para a sua família.</p>
  </div>
  <div style="text-align:center; margin-bottom:200px;">

  <button class="searchbutton"><%= link_to "A minha solução", seguros_path%></button>

  </div>


</div>

app/views/seguroscontacts/create.html.erb
<div class="home">

<div style="padding-top:20%;">


  <h3 class="thank">
    Obrigado pela sua mensagem, entraremos em contacto em breve!
  </h3>




</div>

app/views/seguroscontacts/new.html.erb
<h1 style="font-size: 100px;">NEW<h1>